# Baseline Llama Configuration (Standard Attention)
# Identical setup to fineweb_local_300m_infini_4gpu_config.yaml but with Infini-Attention disabled
# For fair comparison with the Infini-Attention implementation

general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: false
  project: llama_300m_baseline_4gpu_fineweb
  run: 4gpu_fineweb_300m_baseline_experiment
  seed: 42
  step: null

# Infini-Attention Configuration (Disabled for Baseline)
infini_attention:
  segment_length: 2048                  # Same as Infini-Attention config
  turn_on_memory: false                 # DISABLE Infini-Attention memory
  balance_factor_lr: 0.00015           # Keep settings identical (not used when memory is off)
  balance_act_type: hard_sigmoid       # Keep settings identical (not used when memory is off)
  balance_init_type: zeros             # Keep settings identical (not used when memory is off)
  logging: true                        # Enable detailed logging for comparison
  logging_interval: 1000               # Match Infini-Attention config
  log_grad: false                     # Match Infini-Attention config
  log_segment_acts: false             # Match Infini-Attention config
  balance_factor_weight_decay: 0.0    # Match Infini-Attention config

# Model Configuration (300M Parameters - Identical to Infini-Attention Setup)
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.03125  # 1/sqrt(1024)
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    initializer_range: 0.02
    hidden_size: 1024
    intermediate_size: 4096
    num_hidden_layers: 12
    is_llama_config: true
    max_position_embeddings: 32768  # Updated for long context
    num_attention_heads: 8
    num_key_value_heads: 8
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 49152

# Optimizer Configuration - Adjusted for larger model and batch size
optimizer:
  accumulate_grad_in_fp32: true
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-08
  torch_adam_is_fused: false
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.00006  # Reduced for larger model and long sequences
    lr_decay_starting_step: null
    lr_decay_steps: null
    lr_decay_style: cosine
    lr_warmup_steps: 500  
    lr_warmup_style: linear
    min_decay_lr: 0.000006
  weight_decay: 0.1
  zero_stage: 0

# Parallelism Configuration - 4x GPUs with data parallelism
parallelism:
  dp: 4  # Data parallel across 4 GPUs
  tp: 1  # No tensor parallelism
  expert_parallel_size: 1
  pp: 1  # No pipeline parallelism
  pp_engine: 1f1b
  tp_linear_async_communication: false
  tp_mode: ALL_REDUCE

# Tokenizer Configuration
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: lvwerra/the-tokenizer-v1
  tokenizer_revision: null

# Training Tokens Configuration - Adjusted for long sequences
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 1  # Reduced due to very long sequences (32768)
  sequence_length: 8192  # Full reference sequence length
  train_steps: 10000  # Reduced for initial testing
  val_check_interval: -1

# Data Configuration for Local FineWeb Dataset
data_stages:
  - name: "4GPU FineWeb 300M Baseline Stage"
    start_training_step: 1
    data:
      dataset:
        hf_dataset_or_datasets: "parquet"
        hf_dataset_config_name: null
        hf_dataset_splits: "train"
        text_column_name: "text"
        dataset_processing_num_proc_per_process: 4
        dataset_overwrite_cache: false
        data_dir: "/data1/dataset/HuggingFaceFW/tiny/"
      num_loading_workers: 4
      seed: 42

# Checkpoints Configuration
checkpoints:
  checkpoint_interval: 1000  
  checkpoints_path: ./checkpoints/fineweb_4gpu_300m_baseline
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: null
  save_initial_state: true

# Logging Configuration
logging:
  iteration_step_info_interval: 50  
  log_level: info
  log_level_replica: info

# Profiler (disabled for simplicity)
profiler: null

# Experiment Logger (Optional - requires setup)
experiment_logger:
  tensorboard_logger:
    flush_secs: 30
    tensorboard_dir: ./tensorboard_logs/fineweb_4gpu_300m_baseline
  # wandb_logger:  # Uncomment if you have wandb setup
  #   wandb_entity: null
  #   wandb_project: llama_300m_baseline_4gpu_fineweb
