checkpoints:
  checkpoint_interval: 1000
  # Base working directory specified
  checkpoints_path: "/home/data/daal_insight/fiery/Infini-attention/nanotron-infini/checkpoints"
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: null
  save_initial_state: false
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: gpu_infini_attention
  run: infini_llama_gpu_%date_%jobid
  seed: 42
  step: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
infini_attention:
  segment_length: 64
  turn_on_memory: true
  balance_init_type: zeros
  balance_act_type: orig_sigmoid
  balance_factor_lr: 0.001  # Added missing required parameter
  logging: false  # Added missing required parameter
  logging_interval: 100  # Added missing required parameter
  log_grad: false  # Added missing required parameter
  log_segment_acts: false  # Added missing required parameter
model:
  ddp_bucket_cap_mb: 120
  dtype: bfloat16  # Use bfloat16 for GPU training
  init_method:
    std: 0.03125
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    hidden_size: 1024  # Full model size for GPU
    initializer_range: 0.02
    intermediate_size: 4096
    num_hidden_layers: 6
    is_llama_config: true
    max_position_embeddings: 256
    num_attention_heads: 8
    num_key_value_heads: 8
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    rope_theta: 10000.0
    rope_interleaved: false
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 32000
optimizer:
  accumulate_grad_in_fp32: true
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-08
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0001
    lr_decay_starting_step: null
    lr_decay_steps: null
    lr_decay_style: cosine
    lr_warmup_steps: 2000
    lr_warmup_style: linear
    min_decay_lr: 1.0e-05
  torch_adam_is_fused: true  # Use fused Adam for GPU
  weight_decay: 0.1
  zero_stage: 0
parallelism:
  dp: 1
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
data_stages:
  - name: Training Stage
    start_training_step: 1
    data:
      dataset:
        dataset_overwrite_cache: false
        dataset_processing_num_proc_per_process: 4  # Increased for faster processing
        hf_dataset_config_name: null
        # Specific data directory path
        hf_dataset_or_datasets: "/data1/dataset/HuggingFaceFW/processed"
        hf_dataset_splits: train
        text_column_name: text
      num_loading_workers: 4  # Increased for faster data loading
      seed: 42
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: meta-llama/Llama-2-7b-hf
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 4  # Increased for GPU
  sequence_length: 256  # Increased for GPU
  train_steps: 50000
  val_check_interval: 500  # Validate every 500 steps
profiler: null
