# Tiny Test Configuration Using FineWeb Model Settings
# Same model as fineweb_local_200m_infini_config.yaml but with minimal data for testing

general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true  # Skip sanity checks for faster testing
  project: debug_tiny_fineweb_test
  run: tiny_fineweb_test_run_%date_%jobid
  seed: 42
  step: null

# Infini-Attention Configuration (same as fineweb config)
infini_attention:
  segment_length: 64
  turn_on_memory: true
  balance_factor_lr: 0.00015
  balance_act_type: hard_sigmoid
  balance_init_type: zeros
  logging: true
  logging_interval: 5  # More frequent logging for debugging
  log_grad: false
  log_segment_acts: false

# Model Configuration (200M parameters - same as fineweb config)
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.03125  # 1/sqrt(1024)
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    initializer_range: 0.02
    hidden_size: 1024
    intermediate_size: 4096
    num_hidden_layers: 6
    is_llama_config: true
    max_position_embeddings: 256  # Same as fineweb config
    num_attention_heads: 8
    num_key_value_heads: 8
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 49152  # Same as fineweb config

# Optimizer Configuration (disable fused AdamW to avoid the error)
optimizer:
  accumulate_grad_in_fp32: true
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-08
  torch_adam_is_fused: false  # Disable fused optimizer to avoid error
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.001  # Higher LR for faster testing
    lr_decay_starting_step: null
    lr_decay_steps: 15  # Decay over most of the training steps
    lr_decay_style: cosine
    lr_warmup_steps: 5  # Minimal warmup for testing
    lr_warmup_style: linear
    min_decay_lr: 0.0001
  weight_decay: 0.1  # Same as fineweb config
  zero_stage: 0

# Single GPU Configuration
parallelism:
  dp: 1
  tp: 1
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp_linear_async_communication: false
  tp_mode: ALL_REDUCE

# Tokenizer Configuration (use same tokenizer as fineweb config)
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: lvwerra/the-tokenizer-v1  # Same as fineweb config
  tokenizer_revision: null

# Minimal Training Configuration
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 2  # Smaller batch size for the larger model
  sequence_length: 256  # Same as fineweb config
  train_steps: 20  # Very few steps for quick testing
  val_check_interval: -1

# Use Small Test Dataset (instead of FineWeb)
data_stages:
  - name: "Tiny FineWeb Test Stage"
    start_training_step: 1
    data:
      dataset:
        hf_dataset_or_datasets: "HuggingFaceH4/testing_alpaca_small"  # Small test dataset
        hf_dataset_config_name: null
        hf_dataset_splits: "train"
        text_column_name: "completion"
        dataset_processing_num_proc_per_process: 1
        dataset_overwrite_cache: false
      num_loading_workers: 1
      seed: 42

# Checkpoint Configuration
checkpoints:
  checkpoint_interval: 10  # Save checkpoint at the end
  checkpoints_path: ./debug_checkpoints_fineweb
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: null
  save_initial_state: false  # Skip initial checkpoint for speed

# Verbose Logging for Debugging
logging:
  iteration_step_info_interval: 1  # Log every step
  log_level: info
  log_level_replica: info

# No profiler for simplicity
profiler: null