# Minimal Test Configuration for Quick Training Process Testing
# This config uses a tiny dataset and minimal steps to test the entire training pipeline

general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true  # Skip sanity checks for faster testing
  project: debug_tiny_test
  run: tiny_test_run_%date_%jobid
  seed: 42
  step: null

# Infini-Attention Configuration (minimal for testing)
infini_attention:
  segment_length: 16  # Very small for testing
  turn_on_memory: true
  balance_factor_lr: 0.001  # Higher for faster convergence in testing
  balance_act_type: hard_sigmoid
  balance_init_type: zeros
  logging: true
  logging_interval: 5  # Log frequently for debugging
  log_grad: false
  log_segment_acts: false

# Tiny Model Configuration for Fast Testing
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.02
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    initializer_range: 0.02
    hidden_size: 64    # Very small for fast testing
    intermediate_size: 128  # Very small
    num_hidden_layers: 2   # Minimal layers
    is_llama_config: true
    max_position_embeddings: 128  # Small context for testing
    num_attention_heads: 2  # Minimal heads
    num_key_value_heads: 2
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 1000  # Very small vocab for testing

# Optimizer Configuration (faster convergence for testing)
optimizer:
  accumulate_grad_in_fp32: true
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-08
  torch_adam_is_fused: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.001  # Higher LR for faster testing
    lr_decay_starting_step: null
    lr_decay_steps: null
    lr_decay_style: cosine
    lr_warmup_steps: 5   # Minimal warmup
    lr_warmup_style: linear
    min_decay_lr: 0.0001
  weight_decay: 0.01  # Lower for testing
  zero_stage: 0

# Single GPU Configuration
parallelism:
  dp: 1
  tp: 1
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp_linear_async_communication: false
  tp_mode: ALL_REDUCE

# Tokenizer Configuration
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: gpt2  # Simple, readily available tokenizer
  tokenizer_revision: null

# Minimal Training Configuration
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 2  # Very small batch for testing
  sequence_length: 64  # Short sequences for fast testing
  train_steps: 20      # Very few steps for quick testing
  val_check_interval: -1

# Use Small Test Dataset
data_stages:
  - name: "Tiny Test Stage"
    start_training_step: 1
    data:
      dataset:
        hf_dataset_or_datasets: "HuggingFaceH4/testing_alpaca_small"  # Small test dataset
        hf_dataset_config_name: null
        hf_dataset_splits: "train"
        text_column_name: "completion"
        dataset_processing_num_proc_per_process: 1
        dataset_overwrite_cache: false
      num_loading_workers: 1
      seed: 42

# Checkpoint Configuration
checkpoints:
  checkpoint_interval: 10  # Save checkpoint at the end
  checkpoints_path: ./debug_checkpoints
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: null
  save_initial_state: false  # Skip initial checkpoint for speed

# Verbose Logging for Debugging
logging:
  iteration_step_info_interval: 1  # Log every step
  log_level: info
  log_level_replica: info

# No profiler for simplicity
profiler: null