# Complete Configuration for Local FineWeb Dataset with Llama 200M + Infini-Attention
# Based on exp53 but adapted for local dataset and simplified for single-user setup

general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: false
  project: llama_200m_infini_local_fineweb
  run: local_fineweb_experiment
  seed: 42
  step: null

# Infini-Attention Configuration
infini_attention:
  segment_length: 64
  turn_on_memory: true
  balance_factor_lr: 0.00015
  balance_act_type: hard_sigmoid
  balance_init_type: zeros
  logging: true
  logging_interval: 1000
  log_grad: false
  log_segment_acts: false

# Model Configuration (200M parameters)
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.03125  # 1/sqrt(1024)
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    initializer_range: 0.02
    hidden_size: 1024
    intermediate_size: 4096
    num_hidden_layers: 6
    is_llama_config: true
    max_position_embeddings: 256  # Increased for longer context
    num_attention_heads: 8
    num_key_value_heads: 8
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 49152

# Optimizer Configuration
optimizer:
  accumulate_grad_in_fp32: true
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-08
  torch_adam_is_fused: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0000375
    lr_decay_starting_step: null
    lr_decay_steps: null
    lr_decay_style: cosine
    lr_warmup_steps: 2000  # Reduced for smaller training
    lr_warmup_style: linear
    min_decay_lr: 0.00000375
  weight_decay: 0.1
  zero_stage: 0

# Parallelism Configuration (adjust based on your GPU setup)
parallelism:
  dp: 1  # Start with single GPU first
  tp: 1  # Tensor parallelism
  expert_parallel_size: 1
  pp: 1  # Pipeline parallelism
  pp_engine: 1f1b
  tp_linear_async_communication: false
  tp_mode: ALL_REDUCE

# Tokenizer Configuration
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: lvwerra/the-tokenizer-v1  # Use same tokenizer as original
  tokenizer_revision: null

# Training Tokens Configuration
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 4  # Reduced for single GPU - adjust based on your GPU memory
  sequence_length: 256
  train_steps: 20000  # Reduced for testing - increase as needed
  val_check_interval: -1

# Data Configuration for Local FineWeb Dataset
data_stages:
  - name: "Local FineWeb Training Stage"
    start_training_step: 1
    data:
      dataset:
        hf_dataset_or_datasets: "parquet"  # Use parquet loader
        hf_dataset_config_name: null
        hf_dataset_splits: "train"
        text_column_name: "text"  # FineWeb uses "text" column
        dataset_processing_num_proc_per_process: 4
        dataset_overwrite_cache: false
        data_dir: "/data1/dataset/HuggingFaceFW/fineweb/"  # YOUR LOCAL PATH
      num_loading_workers: 4
      seed: 42

# Checkpoints Configuration
checkpoints:
  checkpoint_interval: 2000
  checkpoints_path: ./checkpoints/fineweb_local_200m_infini
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: null
  save_initial_state: false

# Logging Configuration
logging:
  iteration_step_info_interval: 100
  log_level: info
  log_level_replica: info

# Profiler (disabled for simplicity)
profiler: null

# Note: TensorBoard logging not available in this version of nanotron
# Monitor training progress through console output and checkpoints